export enum Routes {
  default = '/',
  home = '/home',
  about = '/about',
  news = '/news',
  newsdetail = '/news/detail',
  products = '/products',
  productdetail = '/products/detail',
  contact = '/contact',
  search = '/search',
  signin = '/sign-in',
  signup = '/sign-up',
  personal = '/personal',
  newpassword = '/new-password',
  addcard = '/add-card',
  carddetail = '/card-detail',
  resetpassword = '/reset-password',
  resetpasswordcode = '/reset-password-code',
}
